name: Deploy to Railway

on:
  push:
    branches:
      - main  # Trigger deployment when code is pushed to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"  # Use Python 3.9

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Install Railway CLI
      - name: Install Railway CLI
        run: npm install -g @railway/cli

      # Step 5: Log in to Railway using the token
      - name: Log in to Railway
        run: railway login ${{ secrets.RAILWAY_TOKEN }}

      # Step 6: Deploy to Railway
      - name: Deploy to Railway
        run: railway up --detach
